---
version: "3"

services:
  asf:
    image: justarchi/archisteamfarm
    container_name: asf
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/asf:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asf.entrypoints=https"
      - "traefik.http.routers.asf.rule=Host(`asf.local.cawnj.dev`)"
      - "traefik.http.services.asf.loadbalancer.server.port=1242"
    networks:
      - proxy

networks:
  proxy:
    external: true
