---
version: "2.1"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /etc/config/sonarr:/config
      - /export/leo/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
