---
version: "2.1"

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/tautulli:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.local.cawnj.dev`)"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    networks:
      - proxy

networks:
  proxy:
    external: true
