---
version: "2.1"

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /etc/config/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
