version: "3.7"

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/qbittorrent:/config
      - /mnt/drive/data/qbittorrent:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.local.cawnj.dev`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true

