---
version: "3.8"

services:
  ariang:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    ports:
      - 6880:6880
    logging:
      driver: json-file
      options:
        max-size: 1m
    restart: unless-stopped
