---
version: "2.1"

services:
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/overseerr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=https"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.cawnj.dev`)"
      - "traefik.http.routers.overseerr.tls.certresolver=cloudflare"
      - "traefik.http.routers.overseerr.tls.domains[0].main=cawnj.dev"
      - "traefik.http.routers.overseerr.tls.domains[0].sans=*.cawnj.dev"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    networks:
      - proxy

networks:
  proxy:
    external: true
