---
version: "2.1"

services:
  pyload:
    image: lscr.io/linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /etc/config/pyload:/config
      - /export/leo/data/downloads:/downloads
    ports:
      - 8001:8000
    restart: unless-stopped
