---
version: "3.8"

services:
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=${RPC_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=false
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/aria2:/config
      - /mnt/drive/data/downloads:/data/downloads
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aria2.entrypoints=https"
      - "traefik.http.routers.aria2.rule=Host(`aria2.local.cawnj.dev`)"
      - "traefik.http.services.aria2.loadbalancer.server.port=6800"
    networks:
      - proxy

  ariang:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ariang.entrypoints=https"
      - "traefik.http.routers.ariang.rule=Host(`ariang.local.cawnj.dev`)"
      - "traefik.http.services.ariang.loadbalancer.server.port=6880"
    networks:
      - proxy

networks:
  proxy:
    external: true
