---
version: "3.8"

services:
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=${RPC_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=false
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/aria2:/config
      - /mnt/drive/data/downloads:/downloads
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    logging:
      driver: json-file
      options:
        max-size: 1m
    restart: unless-stopped

  ariang:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    ports:
      - 6880:6880
    logging:
      driver: json-file
      options:
        max-size: 1m
    restart: unless-stopped
