---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/drive/config/prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.local.cawnj.dev`)"
      - "traefik.http.routers.prowlarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.prowlarr.tls.domains[0].main=local.cawnj.dev"
      - "traefik.http.routers.prowlarr.tls.domains[0].sans=*.local.cawnj.dev"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
      - proxy

networks:
  proxy:
    external: true

