---
version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
      - PLEX_CLAIM={PLEX_CLAIM}
    network_mode: host
    volumes:
      - /mnt/drive/config/plex:/config
      - /tmp/plex:/transcode
      - /mnt/drive/data/media:/data
