http:
  routers:
    plex:
      rule: "Host(`plex.local.cawnj.dev`)"
      entryPoints:
        - "https"
      middlewares:
        - "plexHeaders"
      service: "plex"
    nomad:
      rule: "Host(`nomad.local.cawnj.dev`)"
      entryPoints:
        - "https"
      middlewares:
        - "nomadHeaders"
      service: "nomad"
  services:
    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.1.201:32400"
    nomad:
      loadBalancer:
         servers:
          - url: "http://192.168.1.201:4646"
  middlewares:
    plexHeaders:
      headers:
        sslRedirect: true
        stsSeconds: "315360000"
        browserXSSFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: false
    nomadHeaders:
      headers:
        customRequestHeaders:
          Origin: "https://nomad.local.cawnj.dev"
