http:
  routers:
    api:
      rule: "Host(`traefik.local.cawnj.dev`)"
      entryPoints:
        - "https"
      middlewares:
        - "simpleAuth"
      tls:
        certResolver: "cloudflare"
        domains:
          - main: "local.cawnj.dev"
            sans: "*.local.cawnj.dev"
      service: "api@internal"
    plex:
      rule: "Host(`plex.local.cawnj.dev`)"
      entryPoints:
        - "https"
      middlewares:
        - "plexHeaders"
      tls:
        certResolver: "cloudflare"
        domains:
          - main: "local.cawnj.dev"
            sans: "*.local.cawnj.dev"
      service: "plex"
  services:
    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.1.201:32400"
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - "admin:$apr1$wYFGGUSw$M2qdXMblGxAh579o723Hx0"
    plexHeaders:
      headers:
        sslRedirect: true
        stsSeconds: "315360000"
        browserXSSFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: false
