http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - "admin:$apr1$wYFGGUSw$M2qdXMblGxAh579o723Hx0"
  routers:
    api:
      rule: Host(`traefik.local.cawnj.dev`)
      entrypoints:
        - "https"
      middlewares:
        - "simpleAuth"
      service: "api@internal"
      tls:
        certResolver: "cloudflare"
