http:
  routers:
    bulbaserver:
      rule: "Host(`joaopereira.ie`) || Host(`*.joaopereira.ie`)"
      servie: "bulbaserver"
      tls: {}
    plex:
      rule: "Host(`plex.local.cawnj.dev`)"
      entryPoints:
        - "https"
      middlewares:
        - "plexHeaders"
      service: "plex"
    nomad:
      rule: "Host(`nomad.local.cawnj.dev`)"
      entryPoints:
        - "https"
      middlewares:
        - "nomadHeaders"
      service: "nomad"
    webhook:
      rule: "Host(`webhook.plusvasis.xyz`)"
      entryPoints:
        - "https"
      service: "webhook"
    jellyfin:
      rule: "Host(`jellyfin.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "jellyfin"
    atlas:
      rule: "Host(`synology.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "synology"
    sonarr:
      rule: "Host(`sonarr.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "sonarr"
    radarr:
      rule: "Host(`radarr.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "radarr"
    prowlarr:
      rule: "Host(`prowlarr.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "prowlarr"
    ariang:
      rule: "Host(`ariang.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "ariang"
    aria2:
      rule: "Host(`aria2.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "aria2"
    rdtclient:
      rule: "Host(`rdtclient.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "rdtclient"
    tautulli:
      rule: "Host(`tautulli.local.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "tautulli"
    overseerr:
      rule: "Host(`overseerr.local.cawnj.dev`) || Host(`overseerr.cawnj.dev`)"
      entryPoints:
        - "https"
      service: "overseerr"
  services:
    bulbaserver:
      loadBalancer:
        servers:
          - url: "https://192.168.1.111:443"
        serversTransport: bulbaserver
    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:32400"
    nomad:
      loadBalancer:
        servers:
          - url: "http://192.168.1.201:4646"
    webhook:
      loadBalancer:
        servers:
          - url: "http://192.168.1.201:9000"
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.1.201:8096"
    synology:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:5000"
    sonarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:8989"
    radarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:7878"
    prowlarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:9696"
    ariang:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:6880"
    aria2:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:6800"
    rdtclient:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:6500"
    tautulli:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:8181"
    overseerr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.137:5055"
  serversTransports:
    bulbaserver:
      insecureSkipVerify: true
  middlewares:
    plexHeaders:
      headers:
        sslRedirect: true
        stsSeconds: "315360000"
        browserXSSFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: false
    nomadHeaders:
      headers:
        customRequestHeaders:
          Origin: "https://nomad.local.cawnj.dev"
