entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

api:
  dashboard: true

certificatesResolvers:
  cloudflare:
    acme:
      storage: acme.json
      dnsChallenge:
        provider: cloudflare

providers:
  docker:
    watch: true
    network: "proxy"
    exposedbydefault: false
  file:
    filename: traefik_dynamic.yml
