http:
  routers:
    api:
      rule: "Host(`traefik.local.cawnj.dev`)"
      entryPoints:
        - "https"
      middlewares:
        - "simpleAuth"
      tls:
        certResolver: "cloudflare"
        domains:
          - main: "local.cawnj.dev"
            sans: "*.local.cawnj.dev"
      service: "api@internal"

  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - "admin:$apr1$wYFGGUSw$M2qdXMblGxAh579o723Hx0"
