---
version: "2.1"

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/radarr:/config
      - /mnt/drive/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local.cawnj.dev`)"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.radarr.tls.domains[0].main=local.cawnj.dev"
      - "traefik.http.routers.radarr.tls.domains[0].sans=*.local.cawnj.dev"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - proxy

networks:
  proxy:
    external: true
