---
version: "2.1"

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /export/leo/config/radarr:/config
      - /export/leo/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
