version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - '5672:5672'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.entrypoints=https"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.local.cawnj.dev`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    networks:
      - proxy

networks:
  proxy:
    external: true

