version: "3"

services:
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    restart: unless-stopped
    environment:
      NB_UID: 1000
      NB_GID: 1000
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'
      JUPYTER_TOKEN: '${JUPYTER_TOKEN}'
    volumes:
      - /mnt/drive/data/jupyter:/home/jovyan/work
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.entrypoints=https"
      - "traefik.http.routers.jupyter.rule=Host(`jupyter.local.cawnj.dev`)"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
    networks:
      - proxy

networks:
  proxy:
    external: true

