---
version: "2"

services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    restart: unless-stopped
    command:
      - --base=/
      - --ssh-host=192.168.0.201
      - --ssh-key=/root/.ssh/ssh-key
      - --ssh-auth=publickey
    volumes:
      - /mnt/drive/config/wetty/ssh-key:/root/.ssh/ssh-key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wetty.entrypoints=https"
      - "traefik.http.routers.wetty.rule=Host(`wetty.cawnj.dev`) || Host(`wetty.local.cawnj.dev`)"
      - "traefik.http.services.wetty.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.simpleAuth.basicauth.users=wetty:$$apr1$$stjnq9km$$YZ.UkrKEC3/AebvezBpLy1"
      - "traefik.http.routers.wetty.middlewares=simpleAuth"
    networks:
      - proxy

networks:
  proxy:
    external: true
