---
version: "2.1"

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/jackett:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.entrypoints=https"
      - "traefik.http.routers.jackett.rule=Host(`jackett.local.cawnj.dev`)"
      - "traefik.http.routers.jackett.tls.certresolver=cloudflare"
      - "traefik.http.routers.jackett.tls.domains[0].main=local.cawnj.dev"
      - "traefik.http.routers.jackett.tls.domains[0].sans=*.local.cawnj.dev"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
    networks:
      - proxy

networks:
  proxy:
    external: true
