---
title: "leo"
subtitle: "Homer"

header: false
footer: ""

defaults:
  layout: "columns"
  colorTheme: "dark"

stylesheet:
  - "assets/custom.css"

columns: "auto" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

# Services
services:
  - name: "Hosting"
    icon: "fas fa-server"
    items:
      - name: "Pihole"
        logo: "homer-icons/png/pihole.png"
        url: "https://pihole.local.cawnj.dev/admin/"
      - name: "Traefik"
        logo: "homer-icons/png/traefik.png"
        url: "https://traefik.local.cawnj.dev/"
  - name: "Download"
    icon: "fas fa-download"
    items:
      - name: "Sonarr"
        logo: "homer-icons/png/sonarr.png"
        url: "https://sonarr.local.cawnj.dev/"
      - name: "Radarr"
        logo: "homer-icons/png/radarr.png"
        url: "https://radarr.local.cawnj.dev/"
      - name: "Prowlarr"
        logo: "homer-icons/png/prowlarr.png"
        url: "https://prowlarr.local.cawnj.dev/"
      - name: "rdt-client"
        logo: "homer-icons/png/qbittorrent.png"
        url: "https://rdtclient.local.cawnj.dev/"
      - name: "AriaNg"
        logo: "homer-icons/png/ariang.png"
        url: "https://ariang.local.cawnj.dev/"
  - name: "Media"
    icon: "fas fa-video"
    items:
      - name: "Plex"
        logo: "homer-icons/png/plex.png"
        url: "https://plex.local.cawnj.dev/"
      - name: "Overseerr"
        logo: "homer-icons/png/overseerr.png"
        url: "https://overseerr.cawnj.dev/"
      - name: "Tautulli"
        logo: "homer-icons/png/tautulli.png"
        url: "https://tautulli.local.cawnj.dev/"
  - name: "Personal"
    icon: "fas fa-user"
    items:
      - name: "Nextcloud"
        logo: "homer-icons/png/nextcloud.png"
        url: "https://nextcloud.cawnj.dev"
      - name: "CodiMD"
        logo: "custom-icons/codimd.png"
        url: "https://md.cawnj.dev"
      - name: "Filehost"
        logo: "custom-icons/filehost.png"
        url: "https://filehost.cawnj.dev"
