---
version: "2"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - /mnt/drive/config/homer:/www/assets
      - ./config.yml:/www/assets/config.yml
      - ./homer-icons:/www/homer-icons
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.rule=Host(`homer.local.cawnj.dev`)"
      - "traefik.http.routers.homer.tls.certresolver=cloudflare"
      - "traefik.http.routers.homer.tls.domains[0].main=local.cawnj.dev"
      - "traefik.http.routers.homer.tls.domains[0].sans=*.local.cawnj.dev"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
