---
version: "2"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - ./homer-theme/assets:/www/assets
      - ./config.yml:/www/assets/config.yml:ro
      - ./homer-icons:/www/homer-icons
      - ./custom-icons:/www/custom-icons
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.rule=Host(`homer.local.cawnj.dev`)"
      - "traefik.http.routers.homer.tls.certresolver=cloudflare"
      - "traefik.http.routers.homer.tls.domains[0].main=local.cawnj.dev"
      - "traefik.http.routers.homer.tls.domains[0].sans=*.local.cawnj.dev"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
