version: '3'

services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    pid: host
    hostname: leo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: "-w"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.entrypoints=https"
      - "traefik.http.routers.glances.rule=Host(`glances.local.cawnj.dev`)"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
    networks:
      - proxy

networks:
  proxy:
    external: true

