version: '3.9'

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_ROUTES: '192.168.0.0/24'
    volumes:
     - '/var/lib:/var/lib'
     - '/dev/net/tun:/dev/net/tun'
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

