version: '3.9'

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    volumes:
     - '/var/lib:/var/lib'
     - '/dev/net/tun:/dev/net/tun'
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

