version: "3"

services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - DELUGE_LOGLEVEL=error
    volumes:
      - /mnt/drive/config/deluge:/config
      - /mnt/drive/downloads/deluge:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.entrypoints=https"
      - "traefik.http.routers.deluge.rule=Host(`deluge.local.cawnj.dev`)"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
    networks:
      - proxy

networks:
  proxy:
    external: true

