version: '3.5'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - '107'
      - '44'
    volumes:
      - /mnt/drive/config/jellyfin:/config
      - /mnt/drive/config/jellyfin/cache:/cache
      - /mnt/drive/data/media:/media:ro
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.local.cawnj.dev
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    network_mode: host

