---
version: "2.1"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Dublin
    ports:
      - 8191:8191
    restart: unless-stopped 
