---
version: "2.1"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    network_mode: host
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - SERVERURL=wireguard.cawnj.dev
      - SERVERPORT=51820
      - PEERS=laptop,phone,external
      - PEERDNS=auto
    volumes:
      - /mnt/drive/config/wireguard:/config
      - /lib/modules:/lib/modules

