---
version: '3.3'

services:
  rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /mnt/drive/config/rdtclient:/data/db
      - /mnt/drive/data/downloads:/data/downloads
    logging:
      driver: json-file
      options:
        max-size: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rdtclient.entrypoints=https"
      - "traefik.http.routers.rdtclient.rule=Host(`rdtclient.local.cawnj.dev`)"
      - "traefik.http.services.rdtclient.loadbalancer.server.port=6500"
    networks:
      - proxy

networks:
  proxy:
    external: true
